### ISSUE TITLE
HTTP requests processing prioritisation

### ISSUE THREAD

**Issue by jkyberneees** [node-muneem/muneem#9]
Allow muneem to optionally process HTTP requests using the Node.js "check" phase, resulting in a bigger performance gain if running in multicore CPU runtimes.

On my local tests performance jumped from 28k requests/secs to 40k...
```
 kyberneees@klab  ~  wrk -t8 -c100 -d10s http://127.0.0.1:3000/hi
Running 10s test @ http://127.0.0.1:3000/hi
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.48ms    1.25ms  35.36ms   97.66%
    Req/Sec     5.03k   676.01     6.62k    94.88%
  400617 requests in 10.01s, 42.79MB read
Requests/sec:  40009.14
Transfer/sec:      4.27MB
```
Same feature in `restana` is described here: https://www.npmjs.com/package/restana#configuration `prioRequestsProcessing `, you can also see the implementation here: https://github.com/jkyberneees/ana/blob/d4b5ffa0f2d0133bbdc06aac6810f4c8fdfeb1b8/index.js#L44

Technical details about `setImmediate` here: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/

Best Regards, Rolando

**Comment by amitguptagwl** [comment]
Thanks a lot for this suggestion. I'll check and try this.

**Comment by amitguptagwl** [comment]
Yes, I've used that approach in my other application [stubmatic](https://porter.io/github.com/NaturalIntelligence/Stubmatic) and it was really helpful. Let me check if I can use it with muneem and what will be the impact.

**Comment by amitguptagwl** [comment]
I didn't see any benefit in case of muneem. Running the previous perf tests that I discussed with you.
```
Running restana with find-my-way
Requests per second:    24296.06 [#/sec] (mean)
Running restana with anumargak
Requests per second:    24296.46 [#/sec] (mean)
Running muneem
Requests per second:    30236.49 [#/sec] (mean)
```

**Comment by jkyberneees** [comment]
Hi Amit, can you share details about the machine specs and the tool you use the measure the performance? 
Wondering because I get totally different results on my side.

**Comment by jkyberneees** [comment]
Hi Amit, unfortunately I can't reliable use the `ab` on my Mac ;(, it just hangs. 
Could you please consider other tools for benchmarking as well. For example: https://blog.loadimpact.com/open-source-load-testing-tool-review
I personally use `wrk`, which supports multi-threading and HTTP 1.1, therefore generates considerable load. Here you will notice considerable differences. 

Looking forward to your feedback here. 
Thanks.

**Comment by amitguptagwl** [comment]
Sure. I'll update you.

**Comment by amitguptagwl** [comment]
Here is the result

Without setImmediate 

```bash
$ ab -k -n 50000 -c 100 -t 20 http://127.0.0.1:3002/this/is/static | grep "Requests per second:"
:
Requests per second:    24124.52 [#/sec] (mean)
$ wrk -t8 -c100 -d10s  "http://127.0.0.1:3002/this/is/static"
Running 10s test @ http://127.0.0.1:3002/this/is/static
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.21ms  370.68us  14.22ms   74.92%
    Req/Sec     3.75k   234.50     4.19k    72.12%
  298593 requests in 10.01s, 29.62MB read
Requests/sec:  29841.63
Transfer/sec:      2.96MB
```

With setImmediate 
```bash
$ ab -k -n 50000 -c 100 -t 20 http://127.0.0.1:3002/this/is/static | grep "Requests per second:"
:
Requests per second:    24351.18 [#/sec] (mean)

$ wrk -t8 -c100 -d10s  "http://127.0.0.1:3002/this/is/static"
Running 10s test @ http://127.0.0.1:3002/this/is/static
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.04ms    1.11ms  16.88ms   85.70%
    Req/Sec     4.00k   347.34     4.67k    79.12%
  318173 requests in 10.01s, 31.56MB read
Requests/sec:  31792.79
Transfer/sec:      3.15MB
```

Do you use hooks or events in restana? Because I use many in Muneem and that can be the reason for not a big difference.

**Comment by jkyberneees** [comment]
In restana there is only one hook at the moment, that is the "response" event. Might be a reason for a bit of performance impact on muneem.

On my Mac, the performance increase with setImmediate is up to 40k r/s in muneem.

**Comment by amitguptagwl** [comment]
Yes. I need events for some plugins like aalekh.
